extends Node
## All audio: buses, volumes, playback (§33, §40).
##
## Owns: the audio bus graph and every volume setting.
## Must never: do anything else.
##
## Buses are created at runtime rather than shipped as a .tres bus layout, so the
## routing lives in readable, diffable code next to the volume logic instead of a
## binary-ish resource nobody can review.
##
## §33 requires conservative defaults and no loud autoplay on first launch. That
## is enforced here: volumes come from GameSettings (which defaults them low) and
## nothing plays until something explicitly asks it to.
##
## Cues are synthesised sines generated by tools/generate_audio.gd — soft,
## pentatonic, and short. §3 rules out anything resembling a mobile-game reward
## jingle, so nothing here is longer than a second or louder than it needs to be.

## Bus names must match the keys used by GameSettings' volume fields.
const BUS_MASTER: StringName = &"Master"
const BUS_MUSIC: StringName = &"Music"
const BUS_AMBIENT: StringName = &"Ambient"
const BUS_UI: StringName = &"UI"
const BUS_TIMER: StringName = &"Timer"

const CHILD_BUSES: Array[StringName] = [BUS_MUSIC, BUS_AMBIENT, BUS_UI, BUS_TIMER]

## Below this a bus is muted outright rather than set to a very small dB value,
## which would still be faintly audible.
const SILENCE_THRESHOLD: float = 0.001

## Cue id -> path. Timer cues route to the Timer bus, everything else to UI, so
## a player who wants completion sounds but no interface clicks can have that.
const CUES: Dictionary = {
	&"ui_click": "res://assets/audio/ui_click.wav",
	&"session_start": "res://assets/audio/session_start.wav",
	&"session_complete": "res://assets/audio/session_complete.wav",
	&"break_complete": "res://assets/audio/break_complete.wav",
	&"level_up": "res://assets/audio/level_up.wav",
	&"plant_matured": "res://assets/audio/plant_matured.wav",
	&"chime_soft": "res://assets/audio/chime_soft.wav",
}
const TIMER_CUES: Array[StringName] = [
	&"session_start", &"session_complete", &"break_complete",
]
## Concurrent one-shot players. Enough that overlapping cues do not cut each
## other off, few enough that nothing can spam the mixer.
const PLAYER_POOL_SIZE: int = 6

var _audio_available: bool = true
var _bus_indices: Dictionary = {}
var _streams: Dictionary = {}
var _players: Array[AudioStreamPlayer] = []
var _next_player: int = 0


func _ready() -> void:
	_setup_buses()
	_load_cues()
	EventBus.save_loaded.connect(_on_save_loaded)
	_connect_cue_events()


## Plays a cue by id. Silently does nothing when audio is unavailable or the cue
## is missing, because a missing sound must never interrupt gameplay (§54's
## unavailable audio device).
func play(cue: StringName) -> void:
	if not _audio_available or not _streams.has(cue) or _players.is_empty():
		return
	var player := _players[_next_player]
	_next_player = (_next_player + 1) % _players.size()
	player.bus = String(BUS_TIMER if TIMER_CUES.has(cue) else BUS_UI)
	player.stream = _streams[cue]
	player.play()


func _load_cues() -> void:
	if not _audio_available:
		return
	for cue: StringName in CUES:
		var path: String = CUES[cue]
		if not ResourceLoader.exists(path):
			GameLog.warn(GameLog.Category.APP, "Missing audio cue: %s" % path)
			continue
		_streams[cue] = load(path)

	for i in PLAYER_POOL_SIZE:
		var player := AudioStreamPlayer.new()
		player.bus = String(BUS_UI)
		add_child(player)
		_players.append(player)


## Game events the player should hear. Kept here rather than in each system so
## the full set of sounds the game makes is legible in one place.
func _connect_cue_events() -> void:
	EventBus.session_started.connect(func(_id: String) -> void: play(&"session_start"))
	EventBus.plant_matured.connect(func(_uid: String) -> void: play(&"plant_matured"))
	EventBus.level_up.connect(func(_level: int) -> void: play(&"level_up"))
	EventBus.plant_stage_changed.connect(
		func(_uid: String, _stage: int) -> void: play(&"chime_soft")
	)
	EventBus.session_completed.connect(_on_session_completed)


func _on_session_completed(session_id: String) -> void:
	for session: FocusSession in AppState.sessions:
		if session.id != session_id:
			continue
		# A discarded session gets no sound: it is not an accomplishment.
		if session.completion == FocusSession.Completion.CANCELLED:
			return
		play(&"break_complete" if session.is_break() else &"session_complete")
		return


## Applies every volume from settings. Called on load and whenever a slider moves.
func apply_settings(settings: GameSettings) -> void:
	if not _audio_available or settings == null:
		return
	set_bus_volume(BUS_MASTER, settings.volume_master)
	set_bus_volume(BUS_MUSIC, settings.volume_music)
	set_bus_volume(BUS_AMBIENT, settings.volume_ambient)
	set_bus_volume(BUS_UI, settings.volume_ui)
	set_bus_volume(BUS_TIMER, settings.volume_timer)


## Sets a bus from a 0..1 linear value, as the settings sliders express it.
func set_bus_volume(bus_name: StringName, linear: float) -> void:
	if not _audio_available or not _bus_indices.has(bus_name):
		return
	var index: int = _bus_indices[bus_name]
	var clamped := clampf(linear, 0.0, 1.0)
	AudioServer.set_bus_mute(index, clamped < SILENCE_THRESHOLD)
	# linear_to_db is the correct conversion: volume sliders are perceptually
	# linear, bus volumes are decibels, and a naive percentage mapping makes the
	# bottom half of every slider do almost nothing.
	AudioServer.set_bus_volume_db(index, linear_to_db(maxf(clamped, SILENCE_THRESHOLD)))


func get_bus_volume(bus_name: StringName) -> float:
	if not _audio_available or not _bus_indices.has(bus_name):
		return 0.0
	return db_to_linear(AudioServer.get_bus_volume_db(_bus_indices[bus_name]))


## True when the system has a usable audio device. §54 requires an unavailable
## audio device to be handled: the game runs silently rather than erroring, and
## the settings screen can explain why the sliders do nothing.
func is_audio_available() -> bool:
	return _audio_available


func _setup_buses() -> void:
	# A machine with no sound device gets the Dummy driver, and headless test runs
	# always do. Bus manipulation is pointless there, and treating it as an error
	# would make the test suite fail for a reason unrelated to the code.
	var driver := AudioServer.get_driver_name()
	if driver == "Dummy":
		_audio_available = false
		GameLog.info(GameLog.Category.APP, "No audio device; running silently.")
		return

	_bus_indices[BUS_MASTER] = 0
	for bus_name: StringName in CHILD_BUSES:
		var existing := AudioServer.get_bus_index(bus_name)
		if existing == -1:
			existing = AudioServer.bus_count
			AudioServer.add_bus(existing)
			AudioServer.set_bus_name(existing, bus_name)
			AudioServer.set_bus_send(existing, BUS_MASTER)
		_bus_indices[bus_name] = existing

	GameLog.debug(GameLog.Category.APP, "Audio buses ready on driver '%s'." % driver)


func _on_save_loaded() -> void:
	apply_settings(AppState.get_settings())
